version: '3.7'
services:
  users:
    build:
      context: .
    networks:
      monitoring:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      monitoring:

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      monitoring:

networks:
  monitoring:

volumes:
  grafana-storage:
